POST http://localhost:4000/user/login
Content-Type: application/json

{
  "username": "kadir",
  "password": "123456"
}

###

POST http://localhost:4000/user/signup
Content-Type: application/json

{
  "username": "kadir",
  "password": "123456"
}

###

POST http://localhost:4000/user/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ikt2b0NZdGV5RXMwaExlSnBoSFRoLSIsImV4cCI6MTY1NzQ4OTQyM30.sYtJcs8TMHVfqJ0XMudBaGKRHw34-GukAKiUU__cSe0"
}

###

POST http://localhost:4000/question
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ikt2b0NZdGV5RXMwaExlSnBoSFRoLSIsImV4cCI6MTY1NzQ4NjY3NH0.nbe_AC0krw58p48MsyoBfE_EIJtdISpoBcwuj1wRjqw
